# Generated by Django 6.0.3 on 2026-04-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.AddField(
            model_name='account',
            name='provider',
            field=models.CharField(default='google', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='provider_id',
            field=models.CharField(default=1234, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
