# Generated by Django 6.0.3 on 2026-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_phone_account_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
