# Generated by Django 6.0.3 on 2026-04-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_provider_alter_account_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.URLField(blank=True, default=''),
        ),
    ]
