# Generated by Django 6.0.3 on 2026-07-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meeting.meeting'),
        ),
    ]
