name: meetscheduler

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - meetscheduler_volume:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis-container
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    restart: unless-stopped
    volumes:
      - meetscheduler_redis_volume:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  meetscheduler_volume:
  meetscheduler_redis_volume:
