# Generated by Django 6.0.3 on 2026-08-24 06:28

from django.db import migrations, models


def delete_reminder_logs(apps, schema_editor):
    EmailNotification = apps.get_model('notifications', 'EmailNotification')
    EmailNotification.objects.filter(notification_type='reminder').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_reminder_logs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('cancellation', 'Cancellation')], max_length=20),
        ),
    ]
